name: orphan_connect
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5

  # State Management
  provider: ^6.1.5+1

  # Image Handling
  image_picker: ^1.2.1
  cached_network_image: ^3.4.1
  http: ^1.6.0
  # UI Enhancements
  smooth_page_indicator: ^2.0.1
  google_fonts: ^7.0.0

  # Utilities
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  timeago: ^3.7.1

  firebase_core: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/icon.png
  #   - images/a_dot_ham.jpeg

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#6C63FF"
  adaptive_icon_foreground: "assets/images/icon.png"

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
